//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcAppWithCRUD.Data.Northwind
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvisorySociety
    {
        public int GroupId { get; set; }
        public string Society_Name { get; set; }
        public Nullable<int> Advisor_Days { get; set; }
        public string Advisor_Email { get; set; }
        public string Advisor_ID { get; set; }
        public string Advisor_Years { get; set; }
        public string Advisor_Address { get; set; }
        public string Advisor_phone { get; set; }
        public string Advisor_Name { get; set; }
        public string Advisor_EmailAddress { get; set; }
    }
}
