//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcAppWithCRUD.Data.Northwind
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvisoryNote
    {
        public int nid { get; set; }
        public string emaddr { get; set; }
        public System.DateTime edate { get; set; }
        public string adlogin { get; set; }
        public string etitle { get; set; }
        public string enotes { get; set; }
        public string notefile { get; set; }
    }
}
