//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcAppWithCRUD.Data.Northwind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        public string Emplid { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Middle_Name { get; set; }
        public string CW_PREF_LAST_NAME { get; set; }
        public string CW_PREF_FIRST_NAME { get; set; }
        public string CW_PREF_MID_NAME { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string Visa_Permit_Type { get; set; }
        public string BirthCountry { get; set; }
        public string Citizen_Country { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string State { get; set; }
        public string Postal { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string Extension { get; set; }
        public string Address1_Other { get; set; }
        public string Address2_Other { get; set; }
        public string City_Other { get; set; }
        public string State_Other { get; set; }
        public string Postal_Other { get; set; }
        public string Country_Other { get; set; }
        public string CW_Phone_Other { get; set; }
        public string CW_Extension { get; set; }
        public string Email_Addr { get; set; }
        public string Campus_Id { get; set; }
        public string CW_CELL_PHONE { get; set; }
        public string CW_CC_GIC_DESCR { get; set; }
        public string CW_CC_PRONOUN_DESCR { get; set; }
    }
}
