//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcAppWithCRUD.Data.Northwind
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Misc
    {
        public int id { get; set; }
        public string emplid { get; set; }
        public string emaddr { get; set; }
        public string stpict { get; set; }
        public string stsound { get; set; }
        public string aamc_id { get; set; }
        public string History_comments { get; set; }
        public string reduced_fee { get; set; }
        public string mdt { get; set; }
        public string leave_reason { get; set; }
        public string leave_start_date { get; set; }
        public string leave_end_date { get; set; }
        public Nullable<System.DateTime> mdt_yr1 { get; set; }
        public Nullable<System.DateTime> mdt_yr2 { get; set; }
        public Nullable<System.DateTime> mdt_yr3 { get; set; }
        public Nullable<System.DateTime> mdt_yr4 { get; set; }
        public Nullable<System.DateTime> mdt_yr5 { get; set; }
        public string admission_ethnicity { get; set; }
        public string admission_race { get; set; }
    }
}
