//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMvcAppWithCRUD.Data.Northwind
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Matri_Grad_Dates
    {
        public int id { get; set; }
        public string Emplid { get; set; }
        public string emaddr { get; set; }
        public string Acad_Prog { get; set; }
        public string campuscode { get; set; }
        public string exp_grad_year { get; set; }
        public string mdyr { get; set; }
        public string mdt { get; set; }
        public string gyr { get; set; }
        public Nullable<System.DateTime> gdt { get; set; }
        public Nullable<System.DateTime> Effdt { get; set; }
        public string desk { get; set; }
        public string advisor_name { get; set; }
        public string advisor_email { get; set; }
        public string advisor_campus_id { get; set; }
        public string Prog_status { get; set; }
        public string dcode { get; set; }
        public string ethnicity { get; set; }
        public string priordegrees { get; set; }
        public string mstpprog_status { get; set; }
        public string advisor_society { get; set; }
    }
}
